name: Fetch latest OVH outages data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Fetches repo
        uses: actions/checkout@v2
      - name: Get and format api
        run: |-
          curl https://bare-metal-servers.status-ovhcloud.com/api/v2/summary.json | jq . > bare_metal_cloud_outages.json
          curl https://hosted-private-cloud.status-ovhcloud.com/api/v2/summary.json | jq . > hosted_private_cloud_outages.json
          curl https://network.status-ovhcloud.com/api/v2/summary.json | jq . > network_and_infrastructure_outages.json
          curl https://public-cloud.status-ovhcloud.com/api/v2/summary.json | jq . > public_cloud_outages.json
          curl https://web-cloud.status-ovhcloud.com/api/v2/summary.json | jq . > web_cloud_outages.json
      - name: Add results to repo
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          if git add *.json; then
            # check if there are any changes that are staged but not committed
            if ! git diff --cached --exit-code; then
              git commit -v -m "chore: automated build from $(git rev-parse --short HEAD)"
              git push
            fi
          fi
